---
- name: Ensure Apache is deployed using tags
  hosts: dev
  gather_facts: false
  become: true
  become_user: root
  tasks:
    - name:  Deploy webserver
      yum:
        name: httpd
        state: installed
      tags: ['never', deploy]
    - name:  webserver task
      copy:
        content: "Hello"
        dest: /var/www/html/index.html
      tags: ['never', alpha]
    - name: dataserver task
      copy:
        content: "Bye"
        dest: /var/www/html/index.html
      tags: ['never', beta]
