---
- name: Ensure Apache is deployed using tags
  hosts: production
  gather_facts: false
  tasks:
    - name:  deploy webserver
      yum:
        name: httpd
        state: installed
    - name:  webserver task
      copy:
        content: "webserver"
        dest: /var/www/html/index.html
      tags: ['never', alpha]
    - name: dataserver task
      copy:
        content: "database"
        dest: /var/www/html/index.html
      tags: ['never', beta]
