---
- name: Ensure Apache is deployed
  hosts: all
  gather_facts: false
  tasks:
    - name: first tag task
      copy:
        content: "Hello"
        dest: /var/www/html/index.html
      tags: ['never', alpha]
    - name: second tag task
      copy:
        content: "Bye"
        dest: /var/www/html/index.html
      tags: ['never', beta]
